[package]
name = "csi-test"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csi = { path = "../csi", features = ["full", "nightly_full"] }